#!/usr/bin/env python3
"""Evaluate the frozen ensemble once on fold 9 and write a Kaggle submission.

This script deliberately has no weight search, calibration fitting, training,
or hyperparameter arguments. It reads the fixed values from
``configs/final_model.json`` and applies them to raw probabilities generated by
the two frozen checkpoints.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any, Sequence

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, log_loss


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))

from pmldl_llm.submission import write_submission


CLASS_COLUMNS = ("winner_model_a", "winner_model_b", "winner_tie")
EPSILON = 1e-15


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        type=Path,
        default=PROJECT_ROOT / "configs" / "final_model.json",
        help="Frozen final-model configuration.",
    )
    parser.add_argument(
        "--fold9-predictions",
        type=Path,
        nargs=2,
        required=True,
        metavar=("DEBERTA_CSV", "SPARSE_CSV"),
        help="Raw fold-9 probability CSVs in the frozen model order.",
    )
    parser.add_argument(
        "--test-predictions",
        type=Path,
        nargs=2,
        required=True,
        metavar=("DEBERTA_CSV", "SPARSE_CSV"),
        help="Raw Kaggle-test probability CSVs in the frozen model order.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "results" / "final",
        help="Directory for final metrics, probabilities, and submission.",
    )
    return parser.parse_args()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def normalize(probabilities: np.ndarray) -> np.ndarray:
    values = np.asarray(probabilities, dtype=np.float64)
    if values.ndim != 2 or values.shape[1] != len(CLASS_COLUMNS):
        raise ValueError("Probabilities must have shape (rows, 3).")
    if not np.isfinite(values).all() or (values < 0).any():
        raise ValueError("Probabilities must be finite and non-negative.")
    totals = values.sum(axis=1, keepdims=True)
    if (totals <= 0).any():
        raise ValueError("Every probability row must have positive mass.")
    return values / totals


def load_predictions(path: Path, *, require_target: bool) -> pd.DataFrame:
    frame = pd.read_csv(path)
    required = {"id", *CLASS_COLUMNS}
    if require_target:
        required.add("target")
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"{path} is missing columns: {sorted(missing)}")
    if frame.empty or frame["id"].isna().any() or frame["id"].duplicated().any():
        raise ValueError(f"{path} must have unique, non-null ids.")
    if require_target and not np.isin(frame["target"].to_numpy(), [0, 1, 2]).all():
        raise ValueError(f"{path} target must contain only 0, 1, or 2.")
    checked = frame.loc[:, ["id", *( ["target"] if require_target else [] ), *CLASS_COLUMNS]].copy()
    checked.loc[:, CLASS_COLUMNS] = normalize(
        checked.loc[:, CLASS_COLUMNS].to_numpy(dtype=np.float64)
    )
    return checked


def align_pair(first: pd.DataFrame, second: pd.DataFrame, *, require_target: bool) -> pd.DataFrame:
    aligned_second = second.set_index("id").reindex(first["id"]).reset_index()
    if aligned_second["id"].isna().any() or len(first) != len(second):
        raise ValueError("Prediction files must contain exactly the same ids.")
    if require_target and not np.array_equal(
        first["target"].to_numpy(), aligned_second["target"].to_numpy()
    ):
        raise ValueError("Fold-9 targets differ between prediction files.")
    return aligned_second


def temperature_scale(probabilities: np.ndarray, temperature: float) -> np.ndarray:
    if not np.isfinite(temperature) or temperature <= 0:
        raise ValueError("Temperature must be finite and positive.")
    logits = np.log(np.clip(probabilities, EPSILON, 1.0)) / temperature
    logits -= logits.max(axis=1, keepdims=True)
    return normalize(np.exp(logits))


def apply_frozen_ensemble(
    first: pd.DataFrame, second: pd.DataFrame, weights: Sequence[float], temperature: float
) -> np.ndarray:
    if len(weights) != 2 or any(weight <= 0 for weight in weights):
        raise ValueError("The frozen ensemble must contain two positive weights.")
    if not np.isclose(sum(weights), 1.0, atol=1e-12):
        raise ValueError("The frozen ensemble weights must sum to one.")
    blended = (
        weights[0] * first.loc[:, CLASS_COLUMNS].to_numpy(dtype=np.float64)
        + weights[1] * second.loc[:, CLASS_COLUMNS].to_numpy(dtype=np.float64)
    )
    return temperature_scale(normalize(blended), temperature)


def ece_15(targets: np.ndarray, probabilities: np.ndarray) -> float:
    confidence = probabilities.max(axis=1)
    correct = probabilities.argmax(axis=1) == targets
    total = 0.0
    edges = np.linspace(0.0, 1.0, 16)
    for lower, upper in zip(edges[:-1], edges[1:]):
        mask = (confidence > lower) & (confidence <= upper)
        if mask.any():
            total += float(mask.mean()) * abs(
                float(correct[mask].mean()) - float(confidence[mask].mean())
            )
    return total


def evaluate(targets: np.ndarray, probabilities: np.ndarray) -> dict[str, float]:
    one_hot = np.eye(len(CLASS_COLUMNS), dtype=np.float64)[targets]
    predicted = probabilities.argmax(axis=1)
    return {
        "log_loss": float(log_loss(targets, probabilities, labels=[0, 1, 2])),
        "accuracy": float(accuracy_score(targets, predicted)),
        "macro_f1": float(f1_score(targets, predicted, average="macro")),
        "ece_15": ece_15(targets, probabilities),
        "brier_score": float(np.mean(np.sum((probabilities - one_hot) ** 2, axis=1))),
    }


def main() -> None:
    args = parse_args()
    config = json.loads(args.config.read_text(encoding="utf-8"))
    if config.get("status") != "frozen":
        raise ValueError("Final-model config must be frozen before fold-9 evaluation.")
    models = config.get("models", [])
    if [str(model.get("name")) for model in models] != [
        "deberta_qlora_seed42",
        "sparse_tfidf_sprint2",
    ]:
        raise ValueError("Unexpected frozen model order.")
    weights = [float(model["weight"]) for model in models]
    temperature = float(config["calibration"]["temperature"])

    fold9_first = load_predictions(args.fold9_predictions[0], require_target=True)
    fold9_second = align_pair(
        fold9_first,
        load_predictions(args.fold9_predictions[1], require_target=True),
        require_target=True,
    )
    test_first = load_predictions(args.test_predictions[0], require_target=False)
    test_second = align_pair(
        test_first,
        load_predictions(args.test_predictions[1], require_target=False),
        require_target=False,
    )

    fold9_probabilities = apply_frozen_ensemble(
        fold9_first, fold9_second, weights, temperature
    )
    test_probabilities = apply_frozen_ensemble(test_first, test_second, weights, temperature)
    metrics = evaluate(fold9_first["target"].to_numpy(dtype=np.int64), fold9_probabilities)

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(
        {
            "id": fold9_first["id"].to_numpy(),
            "target": fold9_first["target"].to_numpy(),
            **{
                column: fold9_probabilities[:, index]
                for index, column in enumerate(CLASS_COLUMNS)
            },
        }
    ).to_csv(output_dir / "fold9_final_probabilities.csv", index=False)
    write_submission(
        test_first["id"].to_numpy(), test_probabilities, output_dir / "submission.csv"
    )
    payload: dict[str, Any] = {
        "status": "completed",
        "evaluation_role": "final_holdout",
        "fold": 9,
        "models": [model["name"] for model in models],
        "weights": weights,
        "temperature": temperature,
        "metrics": metrics,
        "final_model_sha256": sha256_file(args.config),
        "input_sha256": {
            "deberta_fold9": sha256_file(args.fold9_predictions[0]),
            "sparse_fold9": sha256_file(args.fold9_predictions[1]),
            "deberta_test": sha256_file(args.test_predictions[0]),
            "sparse_test": sha256_file(args.test_predictions[1]),
        },
    }
    (output_dir / "final_holdout_metrics.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps(payload, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
